language: c
os: linux
compiler: gcc
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "sLQFF10EKGIxLqLJHlIF44JqKZNVZP2zJRcAlLgxqoX9zT6zbNOk9eO4tdQe1b4gKRwjArhbkorkuCcn34NLsft+Ye8uVC+btAIlFL6+XLrKzv1vSHSph4lu6dewVYveBJ7dWMwtdL/6zN/wTOOEBPtZOugjUrVG0fa0Jh4oDh8ZYMtE7CQm87DdpXlPN8sY5tXMxfFMrNHqKqA9lcye5X0ePxTuyV81es4WrUG5lcwszop7PVHMdb7N3d52SUAy1B0TcpMLIw0YZl4pNRUzguN6i8y4s6U4g8IzLxyIc6NJgGSJKOTBcgI38pGGFMZL9Z7h/iUXOR/VEmqj45itPBnGUgFlMC+HtKXi5pG7YaDLnWf8rXu41DDFILUVDMlNl0lcoMA1f0tCAQQ4kTPNQFksYHeXVfOHqQtx/EstDF8OyEnZ6fbtOe4QYEDS1rOJaA9TWyivtPIU4MEnzpDnwfICiLjvMoNa73mjxK3/u++TQ0km4gOX7wydJWa6f/fDi4juSxRsjrGMSKe1e1HqTUhV9XcpcdVeuJnXJBAt80XLlpOFStWZC/B1YO0fnKA+KdY9nqzS04gZO4G0RCVRX/YsGzl/OvtCaXROGr7Qr7AI7Ku6q8pSrdIk0J9F7lIORtk+p7ItTpVD4fEk+tZ/oX/Wt7JCx5dKWm1kfdfoXA0="
before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Mithreindeir/Dynzasm"
      description: "Interactive Disassembler"
    notification_email: mithreindeir@gmail.com
    build_command_prepend: ""
    build_command: "make"
    branch_pattern: coverity_scan
script: make
