language: c
os: linux
compiler: gcc
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Mithreindeir/Dynzasm"
      description: "Interactive Disassembler"
    notification_email: mithreindeir@gmail.com
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: coverity_scan
script:
    - make
    - ./dis
    - gcov $(find . -name '*.c' ! -path '*arm*' ! -name 'db*' ! -name 'disk*' ! -name 'ser*')

after_success: bash <(curl -s https://codecov.io/bash)
